# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger: none
pr: none

pool:
  vmImage: 'windows-latest'

steps:

- task: AzureResourceManagerTemplateDeployment@3
  name: InfrastructureDeploy
  inputs:
    deploymentScope: 'Subscription'
    azureResourceManagerConnection: $(AzureServiceConnection)
    subscriptionId: $ServiceConnection
    location: $(AzureLocation)
    templateLocation: 'Linked artifact'
    csmFile: '$(Pipeline.Workspace)/$(TemplateFile)'
    csmParametersFile: '$(Pipeline.Workspace)/$(TemplateParameterFile)'
    overrideParameters: '-enableDisaterRecoveryDeploy $(enableDisaterRecoveryDeploy)'
    deploymentMode: 'Incremental'
    deploymentName: '$(Build.BuildNumber)'   